### ISSUE TITLE
Filters not working under Pandoc v2.17?

### ISSUE THREAD

**Issue by moonimal** [prosegrinder/pandoc-templates#12]
**Describe the bug**
On Mac (OS 12.2.1 and 10.15.7) it appears that filters don't run correctly under Pandoc v2.17 (latest)

**To Reproduce**
1. run ```test/run.sh``` with Pandoc 2.17 (latest) installed on macOS (12.2.1 and 10.15.7 tested)

**Expected behavior**
```contact_name```, ```contact_address```, etc. substitutions do not happen. Earlier version of Pandoc (v2.14) works as expected (see screenshots). Haven't tested 2.15, 2.16.

**Screenshots**
**Pandoc v2.17**
![v2 17](https://user-images.githubusercontent.com/2810640/157958960-a35f0e3a-1e95-47f5-8ea2-d281d4bdab8e.jpg)
**Pandoc v2.14**
![v2 14](https://user-images.githubusercontent.com/2810640/157958976-a9b7d5a0-2f80-4859-b6d3-36cf1eada74f.jpg)

**Environment (please complete the following information):**
 - OS: macOS 12.2.1 and 10.15.7
 - Pandoc Version: 2.17 vs 2.14
 - Version: Pandoc-templates commit de287cf3a0f86884b0d54c2ac0128a6a7ce144f1

**Additional context**

**Comment by moonimal** [comment]
Works fine under older Pandoc version, on multiple OS X versions. Ran into this while installing workflow on newly wiped older Mac, then confirmed under 12.2.1.

I use these templates many times per week. Super useful ...

**Comment by davidlday** [comment]
Thanks for bringing this to my attention. Looking into it, hopefully a quick fix.

**Comment by davidlday** [comment]
Fixed and released.

**Comment by davidlday** [comment]
Adding notes on why these changes were needed. v2.17 of Pandoc had the following breaking changes:

- `MetaInlines` values are marshaled as a [sic] `Inlines` list (See https://github.com/jgm/pandoc/pull/7719)
- `.t` on Metadata values replaced with `pandoc.utils.type` (See https://github.com/jgm/pandoc/pull/7768)
